# Generated by Django 4.2.13 on 2024-07-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_example_programming_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='Programming_Languages',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='Programming_Languages',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
