# Generated by Django 4.2.13 on 2024-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_example_programming_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Database_Management',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
