# Generated by Django 4.2.13 on 2024-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_aboutus_database_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Web_development',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='problem_solving',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
