# Generated by Django 4.2.9 on 2024-08-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_aboutus_web_development_aboutus_problem_solving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='reference_id',
            new_name='new_id',
        ),
    ]
